<a href="https://colab.research.google.com/github/deepkkumar07/Machine-Learning-Projects/blob/main/K_Fold/Startified_cross_fold_validation_on_iris_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# importing basic/required libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, mean_squared_error

In [3]:
import seaborn as sns
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
df['species'] = df['species'].map({'setosa':0, 'versicolor':1, 'virginica':2})

In [7]:
df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [9]:
X= df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

#K-Fold Cross-Validation

**Standard K-Fold Cross-Validation** is a data-splitting technique primarily used for Regression tasks (predicting continuous numbers like housing prices, temperatures, or salaries) where there are no distinct categorical classes to balance.

In [15]:
clf = LogisticRegression(max_iter=1000)
k =5
score = cross_val_score(clf,X,y, cv=k)
score

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [16]:
average_score = np.mean(score)
average_score

np.float64(0.9733333333333334)

# *startified k fold*

**Stratified K-Fold** is a specialized version of K-Fold cross-validation designed specifically for **Classification** problems.

 While regular KFold splits the data randomly, StratifiedKFold ensures that each fold contains roughly the same percentage of each class as the entire dataset.

In [21]:
clf = LogisticRegression(max_iter=1000)
stf = StratifiedKFold(n_splits=5)
score1 = cross_val_score(clf,X,y, cv=stf)
score1

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [22]:
print('avg score', np.mean(score1))

avg score 0.9733333333333334

### Checking for Underfitting and Overfitting

To assess whether the model is underfitting or overfitting, we'll train the `LogisticRegression` classifier on the entire dataset and evaluate its accuracy on the training data. We will then compare this training accuracy to the average cross-validation score previously calculated.

In [23]:
clf_full_data = LogisticRegression(max_iter=1000)
clf_full_data.fit(X, y)

training_accuracy = clf_full_data.score(X, y)
print(f'Training Accuracy: {training_accuracy:.4f}')
print(f'Average Cross-Validation Accuracy: {average_score:.4f}')

if training_accuracy > average_score + 0.05: # A small threshold for comparison
    print('The model might be overfitting: Training accuracy is significantly higher than cross-validation accuracy.')
elif training_accuracy < average_score - 0.05:
    print('The model might be underfitting: Training accuracy is significantly lower than cross-validation accuracy.')
else:
    print('The model appears to have a good balance between bias and variance.')

Training Accuracy: 0.9733
Average Cross-Validation Accuracy: 0.9733
The model appears to have a good balance between bias and variance.